// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type CreateUserParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
}

type CreateUserRow struct {
	ID          string
	Email       string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, `
		INSERT INTO users (email, display_name, password_hash)
		VALUES ($1, $2, $3)
		RETURNING id::text, email, display_name`, arg.Email, arg.DisplayName, arg.PasswordHash)
	var result CreateUserRow
	err := row.Scan(&result.ID, &result.Email, &result.DisplayName)
	return result, err
}

type GetUserByEmailRow struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, `
		SELECT id::text, email, display_name, password_hash
		FROM users
		WHERE email = $1`, email)
	var result GetUserByEmailRow
	err := row.Scan(&result.ID, &result.Email, &result.DisplayName, &result.PasswordHash)
	return result, err
}

type GetUserByIDRow struct {
	ID          string
	Email       string
	DisplayName string
	UPIID       string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, `
		SELECT id::text, email, display_name, upi_id
		FROM users
		WHERE id = $1`, id)
	var result GetUserByIDRow
	err := row.Scan(&result.ID, &result.Email, &result.DisplayName, &result.UPIID)
	return result, err
}

type UpdateUserUPIRow struct {
	ID          string
	Email       string
	DisplayName string
	UPIID       string
}

func (q *Queries) UpdateUserUPI(ctx context.Context, userID, upiID string) (UpdateUserUPIRow, error) {
	row := q.db.QueryRow(ctx, `
		UPDATE users SET upi_id = $2, updated_at = now()
		WHERE id = $1
		RETURNING id::text, email, display_name, upi_id`, userID, upiID)
	var result UpdateUserUPIRow
	err := row.Scan(&result.ID, &result.Email, &result.DisplayName, &result.UPIID)
	return result, err
}

type CreateSessionParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, `
		INSERT INTO auth_sessions (user_id, token_hash, expires_at)
		VALUES ($1, $2, $3)`, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

func (q *Queries) GetUserIDBySessionTokenHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, `
		SELECT user_id::text
		FROM auth_sessions
		WHERE token_hash = $1 AND expires_at > now()`, tokenHash)
	var userID string
	err := row.Scan(&userID)
	return userID, err
}
