// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type UpdateExpenseParams struct {
	ID              string
	PaidByUserID    string
	Description     string
	AmountCents     int64
	Currency        string
	ExpenseDate     string
	GroupID         string
	CreatedByUserID string
}

type UpdateExpenseRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (UpdateExpenseRow, error) {
	row := q.db.QueryRow(ctx, `
		UPDATE expenses
		SET paid_by_user_id = $2, description = $3, amount_cents = $4,
			currency = $5, expense_date = $6, updated_at = now()
		WHERE id = $1 AND group_id = $7 AND created_by_user_id = $8 AND deleted_at IS NULL
		RETURNING id::text, created_at`, arg.ID, arg.PaidByUserID, arg.Description, arg.AmountCents, arg.Currency, arg.ExpenseDate, arg.GroupID, arg.CreatedByUserID)
	var result UpdateExpenseRow
	err := row.Scan(&result.ID, &result.CreatedAt)
	return result, err
}

func (q *Queries) DeleteExpenseSplits(ctx context.Context, expenseID string) error {
	_, err := q.db.Exec(ctx, `DELETE FROM expense_splits WHERE expense_id = $1`, expenseID)
	return err
}
