// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type ListExpensesParams struct {
	GroupID string
	Limit   int
}
type ListExpensesRow struct {
	ID                   string
	Description          string
	AmountCents          int64
	Currency             string
	ExpenseDate          string
	CreatedAt            time.Time
	PayerID              string
	PayerEmail           string
	PayerDisplayName     string
	SplitUserID          string
	SplitUserEmail       string
	SplitUserDisplayName string
	SplitAmountCents     int64
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, `
		WITH expense_page AS (
			SELECT e.id, e.description, e.amount_cents, e.currency, e.expense_date,
			       e.paid_by_user_id, e.created_at
			FROM expenses e WHERE e.group_id = $1 AND e.deleted_at IS NULL
			ORDER BY e.expense_date DESC, e.created_at DESC LIMIT $2
		)
		SELECT ep.id::text, ep.description, ep.amount_cents, ep.currency,
		       ep.expense_date::text, ep.created_at,
		       payer.id::text, payer.email, payer.display_name,
		       split_user.id::text, split_user.email, split_user.display_name,
		       es.amount_cents
		FROM expense_page ep JOIN users payer ON payer.id = ep.paid_by_user_id
		JOIN expense_splits es ON es.expense_id = ep.id JOIN users split_user ON split_user.id = es.user_id
		ORDER BY ep.expense_date DESC, ep.created_at DESC, es.user_id`, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]ListExpensesRow, 0)
	for rows.Next() {
		var item ListExpensesRow
		if err := rows.Scan(&item.ID, &item.Description, &item.AmountCents, &item.Currency, &item.ExpenseDate, &item.CreatedAt, &item.PayerID, &item.PayerEmail, &item.PayerDisplayName, &item.SplitUserID, &item.SplitUserEmail, &item.SplitUserDisplayName, &item.SplitAmountCents); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type CreateExpenseParams struct {
	GroupID         string
	PaidByUserID    string
	CreatedByUserID string
	Description     string
	AmountCents     int64
	Currency        string
	ExpenseDate     string
}
type CreateExpenseRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (CreateExpenseRow, error) {
	row := q.db.QueryRow(ctx, `INSERT INTO expenses (group_id, paid_by_user_id, created_by_user_id, description, amount_cents, currency, expense_date) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id::text, created_at`, arg.GroupID, arg.PaidByUserID, arg.CreatedByUserID, arg.Description, arg.AmountCents, arg.Currency, arg.ExpenseDate)
	var result CreateExpenseRow
	err := row.Scan(&result.ID, &result.CreatedAt)
	return result, err
}

type CreateExpenseSplitParams struct {
	ExpenseID   string
	GroupID     string
	UserID      string
	AmountCents int64
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) error {
	_, err := q.db.Exec(ctx, `INSERT INTO expense_splits (expense_id, group_id, user_id, amount_cents) VALUES ($1, $2, $3, $4)`, arg.ExpenseID, arg.GroupID, arg.UserID, arg.AmountCents)
	return err
}

func (q *Queries) DeleteExpense(ctx context.Context, userID, expenseID, groupID string) (string, error) {
	row := q.db.QueryRow(ctx, `UPDATE expenses SET deleted_at = now(), deleted_by_user_id = $1 WHERE id = $2 AND group_id = $3 AND created_by_user_id = $1 AND deleted_at IS NULL RETURNING id::text`, userID, expenseID, groupID)
	var id string
	err := row.Scan(&id)
	return id, err
}
