// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type CreateGroupParams struct {
	Name            string
	CreatedByUserID string
}

type CreateGroupRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, `
		INSERT INTO groups (name, created_by_user_id)
		VALUES ($1, $2)
		RETURNING id::text, name, created_at`, arg.Name, arg.CreatedByUserID)
	var result CreateGroupRow
	err := row.Scan(&result.ID, &result.Name, &result.CreatedAt)
	return result, err
}

type AddGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, `
		INSERT INTO group_members (group_id, user_id)
		VALUES ($1, $2)`, arg.GroupID, arg.UserID)
	return err
}

type ListGroupsForUserRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListGroupsForUser(ctx context.Context, userID string) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, `
		SELECT g.id::text, g.name, g.created_at
		FROM groups g
		JOIN group_members gm ON gm.group_id = g.id
		WHERE gm.user_id = $1
		ORDER BY g.created_at DESC`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]ListGroupsForUserRow, 0)
	for rows.Next() {
		var item ListGroupsForUserRow
		if err := rows.Scan(&item.ID, &item.Name, &item.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) DeleteGroup(ctx context.Context, groupID, userID string) (string, error) {
	row := q.db.QueryRow(ctx, `
		DELETE FROM groups
		WHERE id = $1
		  AND EXISTS (SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2)
		RETURNING id::text`, groupID, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

func (q *Queries) PurgeDeletedGroupSettlements(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, `DELETE FROM settlements WHERE group_id = $1 AND deleted_at IS NOT NULL`, groupID)
	return err
}

func (q *Queries) PurgeDeletedGroupExpenses(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, `DELETE FROM expenses WHERE group_id = $1 AND deleted_at IS NOT NULL`, groupID)
	return err
}
