// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

const databaseNow = `-- name: DatabaseNow :one
SELECT now()
`

func (q *Queries) DatabaseNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}
