// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type ListGroupMembersRow struct {
	ID          string
	Email       string
	DisplayName string
	UPIID       string
	JoinedAt    time.Time
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, `
		SELECT u.id::text, u.email, u.display_name, u.upi_id, gm.joined_at
		FROM group_members gm
		JOIN users u ON u.id = gm.user_id
		WHERE gm.group_id = $1
		ORDER BY gm.joined_at ASC`, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]ListGroupMembersRow, 0)
	for rows.Next() {
		var item ListGroupMembersRow
		if err := rows.Scan(&item.ID, &item.Email, &item.DisplayName, &item.UPIID, &item.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) AddGroupMemberReturning(ctx context.Context, arg AddGroupMemberParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, `
		INSERT INTO group_members (group_id, user_id)
		VALUES ($1, $2)
		RETURNING joined_at`, arg.GroupID, arg.UserID)
	var joinedAt time.Time
	err := row.Scan(&joinedAt)
	return joinedAt, err
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, `
		SELECT EXISTS (SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2)`, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type IsGroupMemberParams struct {
	GroupID string
	UserID  string
}
