// Code generated by sqlc. DO NOT EDIT.

package sqlc

import "context"

func (q *Queries) DeleteSession(ctx context.Context, userID string, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, `
		DELETE FROM auth_sessions
		WHERE user_id = $1 AND token_hash = $2`, userID, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
