// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"time"
)

type CreateSettlementParams struct {
	GroupID          string
	PaidByUserID     string
	ReceivedByUserID string
	AmountCents      int64
	Currency         string
	SettledAt        time.Time
	Note             string
}

type CreateSettlementRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (CreateSettlementRow, error) {
	row := q.db.QueryRow(ctx, `
		INSERT INTO settlements (
			group_id, paid_by_user_id, received_by_user_id, amount_cents,
			currency, settled_at, note
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id::text, created_at`, arg.GroupID, arg.PaidByUserID, arg.ReceivedByUserID, arg.AmountCents, arg.Currency, arg.SettledAt, arg.Note)
	var result CreateSettlementRow
	err := row.Scan(&result.ID, &result.CreatedAt)
	return result, err
}

type DeleteSettlementParams struct {
	DeletedByUserID string
	ID              string
	GroupID         string
}

func (q *Queries) DeleteSettlement(ctx context.Context, arg DeleteSettlementParams) (string, error) {
	row := q.db.QueryRow(ctx, `
		UPDATE settlements
		SET deleted_at = now(), deleted_by_user_id = $1
		WHERE id = $2 AND group_id = $3 AND paid_by_user_id = $1 AND deleted_at IS NULL
		RETURNING id::text`, arg.DeletedByUserID, arg.ID, arg.GroupID)
	var id string
	err := row.Scan(&id)
	return id, err
}
